"""initial schema

Revision ID: a85dd8b164a9
Revises: 
Create Date: 2026-05-18 04:16:26.733022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a85dd8b164a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('university', 'tvet_college', 'nsfas', name='institution_type'), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'inactive', name='institution_status'), nullable=False),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_code')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rsa_id_number', sa.String(length=13), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rsa_id_number')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('STUDENT_REGISTRATION_SUBMITTED', 'STUDENT_RESULTS_SUBMITTED', 'STUDENT_DEREGISTERED', 'FUNDING_DECISION_ISSUED', 'DISBURSEMENT_SCHEDULED', 'DISBURSEMENT_STATUS_UPDATED', 'FUNDING_SUSPENDED', name='event_type'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='event_direction'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATING', 'VALID', 'INVALID', 'FORWARDED', 'ACKNOWLEDGED', 'FAILED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nsfas_reference', sa.Text(), nullable=True),
    sa.Column('parent_event_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['parent_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_institution_enrolments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('institution_student_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deregistered', 'transferred_out', 'graduated', 'suspended', name='enrolment_status'), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('qualification_name', sa.Text(), nullable=False),
    sa.Column('nqf_level', sa.Integer(), nullable=True),
    sa.Column('total_qualification_credits', sa.Integer(), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('accommodation_type', sa.Enum('institution_catered', 'institution_self_catering', 'private_accredited', 'home_commuter', name='accommodation_type'), nullable=True),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'institution_student_number', 'academic_year')
    )
    op.create_table('disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('allowance_type', sa.Enum('tuition', 'accommodation', 'living', 'transport', 'learning_material', 'personal_care', 'disability_assistive', 'disability_human_support', name='allowance_type'), nullable=False),
    sa.Column('amount_rands', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('payment_period', sa.Text(), nullable=False),
    sa.Column('payment_channel', sa.Enum('direct_to_student', 'direct_to_institution', 'direct_to_accommodation_provider', name='payment_channel'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'processed', 'failed', 'held', 'reversed', name='disbursement_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_status_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('RECEIVED', 'VALIDATING', 'VALID', 'INVALID', 'FORWARDED', 'ACKNOWLEDGED', 'FAILED', 'CANCELLED', name='event_status'), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'VALIDATING', 'VALID', 'INVALID', 'FORWARDED', 'ACKNOWLEDGED', 'FAILED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('PASS', 'FAIL', 'WARNING', name='validation_outcome'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    op.drop_table('event_status_log')
    op.drop_table('disbursements')
    op.drop_table('student_institution_enrolments')
    op.drop_table('events')
    op.drop_table('students')
    op.drop_table('institutions')
    # ### end Alembic commands ###